---
title: "Budget History"
author: "Joseph C. Ballenger, PhD"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: "hide"
    dev: "png"
    fig_height: 4.5
    fig_width: 6.5
    highllight: "tango"
    keep_md: TRUE
    smart: TRUE
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    df_print: "paged"
  pdf_document:
    toc: TRUE
    toc_depth: 2
    fig.width: 13.33
    fig.height: 7.5
    fig.crop: TRUE
    dev: "png"
    df_print: "tibble"
    highlight: "tango"
    keep_tex: TRUE
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# knitr options setting
knitr::opts_chunk$set(autodep = TRUE, fig.show = 'asis', fig.width = 13.33,
                      fig.height = 7.5, dev = "png", tidy = TRUE, 
                      dev.args = list(type = "windows", family = "serif"), 
                      dpi = 800, cache = TRUE, message = FALSE, echo = TRUE,
                      warning = FALSE)
# Number printing options
options(digits = 4)
# Required libraries
library(tidyverse)
library(FSA)
library(extrafont)
library(readxl)
library(survey)
```

```{r}
fig.width.powerpoint <- 13.33
fig.height.powerpoint <- 7.5
fig.width.word.l <- 6.5
fig.width.word.p <- 9
fig.height.word.l <- 3.5
fig.height.word.p <- 6

font.size.word <- 12
font.size.powerpoint <- 18
```

```{r}
Budget <- read_excel("Budget History.xlsx")
```

```{r}
Budget2 <- Budget %>%
  select(-Notes) %>%
  select(-Total) %>%
  filter(`Fiscal Year` != "Total") %>%
  mutate(`Fiscal Year` = as.numeric(`Fiscal Year`)) %>%
  gather(key = "Source", value = "Funds", COASTSPAN:Other) %>%
  mutate(Funds = ifelse(is.na(Funds), 0, Funds),
         factor = ordered(Source, levels = c("Other", "Morgan Island", "COASTSPAN", "IJ", "SEAMAP", "RecFIN", 
                                            "SRFAC")))
```

```{r}
Budget3 <- Budget2 %>%
  group_by(`Fiscal Year`) %>%
  summarize(Funds = sum(Funds))
```

```{r}
lm1 <- lm(Funds ~ `Fiscal Year`, data = Budget3[Budget3$`Fiscal Year` %in% seq(2003, 2007), ])
coef(lm1)
p1 <- predict(lm1, newdata = list(`Fiscal Year` = seq(2003, 2007)))
```

```{r}
lm2 <- lm(Funds ~ `Fiscal Year`, data = Budget3[Budget3$`Fiscal Year` %in% seq(2007, 2019), ])
coef(lm2)
p2 <- predict(lm2, newdata = list(`Fiscal Year` = seq(2007, 2019)))
```

```{r, fig.wdith = 13.33, fig.height = 7.5}
ggplot(Budget2, aes(x = `Fiscal Year`, y = Funds / 1000)) +
  geom_area(aes(fill = Source)) +
  geom_smooth(data = Budget3[Budget3$`Fiscal Year` %in% seq(2003, 2007), ], method = "lm", color = "black",
              lwd = 2, size = 5) +
  geom_text(aes(label = "Increase ~ $85,963/year\nAverage Annual % Increase of 33.8%", x = 2005, y = 600), 
            color = "black") +
  geom_smooth(data = Budget3[Budget3$`Fiscal Year` %in% seq(2007, 2019), ], method = "lm", color = "red",
              lwd = 2) +
  geom_text(aes(label = "Increase ~ $9,318/year\nAverage Annual % Increase of 1.6%", x =2012.5, y = 650 ), color = "red") +
  theme_bw() +
  labs(y = "Annual Funding ($1,000s)",
       x = "Year") +
  theme(legend.position = "top",
        text = element_text(family = "Calibri", 
                            size = font.size.powerpoint, 
                            face = "bold"))
ggsave("Core Budget Increase - with both regressions.png", height = fig.height.powerpoint, 
       width = fig.width.powerpoint, device = "png", unit = "in", dpi = 600)
```

```{r, fig.wdith = 13.33, fig.height = 7.5}
ggplot(Budget2, aes(x = `Fiscal Year`, y = Funds / 1000)) +
  geom_area(aes(fill = Source)) +
  theme_bw() +
  labs(y = "Annual Funding ($1,000s)",
       x = "Year") +
  theme(legend.position = "top",
        text = element_text(family = "Calibri", 
                            size = font.size.powerpoint, 
                            face = "bold"))
ggsave("Core Budget Increase.png", height = fig.height.powerpoint, 
       width = fig.width.powerpoint, device = "png", unit = "in", dpi = 600)
```

```{r, fig.wdith = 13.33, fig.height = 7.5}
ggplot(Budget2, aes(x = `Fiscal Year`, y = Funds / 1000)) +
  geom_area(aes(fill = Source)) +
  geom_smooth(data = Budget3[Budget3$`Fiscal Year` %in% seq(2003, 2007), ], method = "lm", color = "black",
              lwd = 2, size = 5) +
  geom_text(aes(label = "Increase ~ $85,963/year\nAverage Annual % Increase of 33.8%", x = 2005, y = 600), 
            color = "black") +
  theme_bw() +
  labs(y = "Annual Funding ($1,000s)",
       x = "Year") +
  theme(legend.position = "top",
        text = element_text(family = "Calibri", 
                            size = font.size.powerpoint, 
                            face = "bold"))
ggsave("Core Budget Increase - with early regression.png", height = fig.height.powerpoint, 
       width = fig.width.powerpoint, device = "png", unit = "in", dpi = 600)
```

```{r}
Budget4 <- Budget2 %>%
  filter(Source %in% c("SRFAC", "RecFIN", "SEAMAP"))
```

```{r}
Budget5 <- Budget4 %>%
  group_by(`Fiscal Year`) %>%
  summarize(Funds = sum(Funds))
```

```{r}
lm3 <- lm(Funds ~ `Fiscal Year`, data = Budget5[Budget5$`Fiscal Year` %in% seq(2003, 2007), ])
coef(lm3)
p3 <- predict(lm3, newdata = list(`Fiscal Year` = seq(2003, 2007)))
```

```{r}
lm4 <- lm(Funds ~ `Fiscal Year`, data = Budget5[Budget5$`Fiscal Year` %in% seq(2007, 2019), ])
coef(lm4)
p4 <- predict(lm4, newdata = list(`Fiscal Year` = seq(2007, 2019)))
```

```{r, fig.wdith = 13.33, fig.height = 7.5}
ggplot(Budget4, aes(x = `Fiscal Year`, y = Funds / 1000)) +
  geom_area(aes(fill = Source)) +
  geom_smooth(data = Budget5[Budget5$`Fiscal Year` %in% seq(2003, 2007), ], method = "lm", color = "black",
              lwd = 2, size = 5) +
  geom_text(aes(label = "Increase ~ $70,616/year\nAverage Annual % Increase of 27.8%", x = 2005, y = 600), 
            color = "black") +
  geom_smooth(data = Budget5[Budget5$`Fiscal Year` %in% seq(2007, 2019), ], method = "lm", color = "red",
              lwd = 2) +
  geom_text(aes(label = "Increase ~ $14,325/year\nAverage Annual % Increase of 2.9%", x =2012.5, y = 650 ), color = "red") +
  theme_bw() +
  labs(y = "Annual Funding ($1,000s)",
       x = "Year") +
  theme(legend.position = "top",
        text = element_text(family = "Calibri", 
                            size = font.size.powerpoint, 
                            face = "bold"))
ggsave("RecFIN, SRFAC, and sEAMAP Increase - with both regressions.png", height = fig.height.powerpoint, 
       width = fig.width.powerpoint, device = "png", unit = "in", dpi = 600)
```

```{r, fig.wdith = 13.33, fig.height = 7.5}
ggplot(Budget4, aes(x = `Fiscal Year`, y = Funds / 1000)) +
  geom_area(aes(fill = Source)) +
  theme_bw() +
  labs(y = "Annual Funding ($1,000s)",
       x = "Year") +
  theme(legend.position = "top",
        text = element_text(family = "Calibri", 
                            size = font.size.powerpoint, 
                            face = "bold"))
ggsave("RecFIN, SRFAC, and sEAMAP Increase.png", height = fig.height.powerpoint, 
       width = fig.width.powerpoint, device = "png", unit = "in", dpi = 600)
```

```{r, fig.wdith = 13.33, fig.height = 7.5}
ggplot(Budget4, aes(x = `Fiscal Year`, y = Funds / 1000)) +
  geom_area(aes(fill = Source)) +
  geom_smooth(data = Budget5[Budget5$`Fiscal Year` %in% seq(2003, 2007), ], method = "lm", color = "black",
              lwd = 2, size = 5) +
  geom_text(aes(label = "Increase ~ $70,616/year\nAverage Annual % Increase of 27.8%", x = 2005, y = 600), 
            color = "black") +
  theme_bw() +
  labs(y = "Annual Funding ($1,000s)",
       x = "Year") +
  theme(legend.position = "top",
        text = element_text(family = "Calibri", 
                            size = font.size.powerpoint, 
                            face = "bold"))
ggsave("RecFIN, SRFAC, and sEAMAP Increase - with early regression.png", height = fig.height.powerpoint, 
       width = fig.width.powerpoint, device = "png", unit = "in", dpi = 600)
```
